### ISSUE TITLE
[Bug] High CPU Usage issue

### ISSUE THREAD

**Issue by Elixir76** [zyrouge/yukino-app#174]
**Describe the bug**
CPU Usage is too high if I play an anime episode then go back

**To Reproduce**

1. Go to 'any anime'
2. Watch it
3. Seek in video then go back
4. CPU Usage goes high while watching and stays high even after going out of the episode (it seems like its still playing but silently), it goes normal if i restart the app

**Expected behavior**
Anime stops working and it stops using system resources

**Screenshots**
![image](https://user-images.githubusercontent.com/63611149/149035608-b380af12-416a-45e8-bdc1-371c059a01f9.png)

**Environment (please complete the following information):**

-   OS: Windows 11
-   Version 21H2

**Additional context**
Also, when I seek in video the audio cuts and I have to click outside of the app then click in app again for it to work
and cpu usage seems... high for video playback if I try watching on the site its much lower

<details>
  <summary>Logs</summary>

[2022-01-12T00:40:34.608867 INFO] AppLifecycle: Starting "preinitialize"
[2022-01-12T00:40:34.624162 INFO] LocalServer: Finished "initialize"
[2022-01-12T00:40:34.624162 INFO] LocalServer: Serving at http://localhost:58503
[2022-01-12T00:40:34.698791 INFO] DataStore: Initialized "ObjectBox"
[2022-01-12T00:40:34.698791 INFO] AppState: Finished "initialize"
[2022-01-12T00:40:34.726758 INFO] AppLifecycle: Finished "preinitialize"
[2022-01-12T00:40:34.726758 INFO] main: Completed "preinitialize"
[2022-01-12T00:40:34.726758 INFO] main: Starting "MainApp"
[2022-01-12T00:40:34.784343 INFO] InstanceManager: Finished "register"
[2022-01-12T00:40:35.045973 INFO] ProtocolHandler: Finished "register"
[2022-01-12T00:40:35.045973 INFO] Screen: Finished "initialize"
[2022-01-12T00:40:47.707072 INFO] VideoPlayerManager: Finished "initialize"
[2022-01-12T00:40:49.658316 INFO] ExtensionsManager: Finished "initialize"
[2022-01-12T00:40:49.658316 INFO] Trackers: Finished "initialize"
[2022-01-12T00:40:58.547524 ERR!] main: Uncaught error: Null check operator used on a null value
  #0      SearchPageController.onInitState (package:yukino_app/ui/pages/search_page/controller.dart:171)
  #1      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:31)
  #2      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:30)
  #3      _rootRunUnary (dart:async/zone.dart:1434)
  <asynchronous suspension>
  
[2022-01-12T00:42:12.695001 ERR!] main: Uncaught error: Null check operator used on a null value
  #0      SearchPageController.onInitState (package:yukino_app/ui/pages/search_page/controller.dart:171)
  #1      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:31)
  #2      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:30)
  #3      _rootRunUnary (dart:async/zone.dart:1434)
  <asynchronous suspension>
  
[2022-01-12T00:42:16.564615 ERR!] main: Uncaught error: Null check operator used on a null value
  #0      SearchPageController.onInitState (package:yukino_app/ui/pages/search_page/controller.dart:171)
  #1      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:31)
  #2      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:30)
  #3      _rootRunUnary (dart:async/zone.dart:1434)
  <asynchronous suspension>
  
[2022-01-12T00:42:34.065665 ERR!] main: Uncaught error: Execution context was destroyed, most likely because of a navigation.
  #0      throwError (package:extensions/hetu/helpers/error.dart:28)
  #1      Function._apply (dart:core-patch/function_patch.dart:11)
  #2      Function.apply (dart:core-patch/function_patch.dart:34)
  #3      HTFunction.call (package:hetu_script/interpreter/function/function.dart:403)
  #4      Hetu._handleCallExpr (package:hetu_script/interpreter/interpreter.dart:915)
  #5      Hetu._handleUnaryPostfixOp (package:hetu_script/interpreter/interpreter.dart:980)
  #6      Hetu._execute (package:hetu_script/interpreter/interpreter.dart:618)
  #7      Hetu.execute (package:hetu_script/interpreter/interpreter.dart:402)
  #8      HTFunction.call (package:hetu_script/interpreter/function/function.dart:308)
  #9      resolveFuture (package:extensions/hetu/helpers/future.dart:29)
  <asynchronous suspension>
  #10     ExtensionInternals.transpileToAnimeExtractor.<anonymous closure> (package:extensions/core/extension.dart:96)
  <asynchronous suspension>
  #11     WatchPageController.fetchSources (package:yukino_app/ui/pages/anime_page/subpages/watch_page/controller.dart:101)
  <asynchronous suspension>
  #12     WatchPageController.ready (package:yukino_app/ui/pages/anime_page/subpages/watch_page/controller.dart:80)
  <asynchronous suspension>
  
[2022-01-12T00:42:51.464949 INFO] select_source: Popping with value
[2022-01-12T00:43:54.848873 INFO] select_source: Popping with value
[2022-01-12T00:45:12.114162 ERR!] main: Uncaught error: Null check operator used on a null value
  #0      SearchPageController.onInitState (package:yukino_app/ui/pages/search_page/controller.dart:171)
  #1      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:31)
  #2      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:30)
  #3      _rootRunUnary (dart:async/zone.dart:1434)
  <asynchronous suspension>
  
[2022-01-12T00:46:49.140634 INFO] AppLifecycle: Starting "preinitialize"
[2022-01-12T00:46:49.157226 INFO] LocalServer: Finished "initialize"
[2022-01-12T00:46:49.157226 INFO] LocalServer: Serving at http://localhost:51208
[2022-01-12T00:46:51.196115 INFO] DataStore: Initialized "ObjectBox"
[2022-01-12T00:46:51.196115 INFO] AppState: Finished "initialize"
[2022-01-12T00:46:51.201064 INFO] AppLifecycle: Finished "preinitialize"
[2022-01-12T00:46:51.201064 INFO] main: Completed "preinitialize"
[2022-01-12T00:46:51.201064 INFO] main: Starting "MainApp"
[2022-01-12T00:46:51.210828 INFO] InstanceManager: Finished "register"
[2022-01-12T00:46:51.373915 INFO] ProtocolHandler: Finished "register"
[2022-01-12T00:46:51.373915 INFO] Screen: Finished "initialize"
[2022-01-12T00:46:53.156750 INFO] VideoPlayerManager: Finished "initialize"
[2022-01-12T00:46:54.333139 INFO] ExtensionsManager: Finished "initialize"
[2022-01-12T00:46:54.334115 INFO] Trackers: Finished "initialize"
[2022-01-12T00:47:03.406924 ERR!] main: Uncaught error: Null check operator used on a null value
  #0      SearchPageController.onInitState (package:yukino_app/ui/pages/search_page/controller.dart:171)
  #1      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:31)
  #2      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:30)
  #3      _rootRunUnary (dart:async/zone.dart:1434)
  <asynchronous suspension>
  
[2022-01-12T00:47:26.706672 ERR!] main: Uncaught error: type '_OneByteString' is not a subtype of type 'List<dynamic>' of '<optimized out>'
  #0      throwError (package:extensions/hetu/helpers/error.dart:28)
  #1      Function._apply (dart:core-patch/function_patch.dart:11)
  #2      Function.apply (dart:core-patch/function_patch.dart:34)
  #3      HTFunction.call (package:hetu_script/interpreter/function/function.dart:403)
  #4      Hetu._handleCallExpr (package:hetu_script/interpreter/interpreter.dart:915)
  #5      Hetu._handleUnaryPostfixOp (package:hetu_script/interpreter/interpreter.dart:980)
  #6      Hetu._execute (package:hetu_script/interpreter/interpreter.dart:618)
  #7      Hetu.execute (package:hetu_script/interpreter/interpreter.dart:402)
  #8      HTFunction.call (package:hetu_script/interpreter/function/function.dart:308)
  #9      resolveFutureAll (package:extensions/hetu/helpers/future.dart:48)
  <asynchronous suspension>
  #10     resolveFuture (package:extensions/hetu/helpers/future.dart:29)
  <asynchronous suspension>
  #11     resolveFuture (package:extensions/hetu/helpers/future.dart:29)
  <asynchronous suspension>
  #12     ExtensionInternals.transpileToAnimeExtractor.<anonymous closure> (package:extensions/core/extension.dart:96)
  <asynchronous suspension>
  #13     WatchPageController.fetchSources (package:yukino_app/ui/pages/anime_page/subpages/watch_page/controller.dart:101)
  <asynchronous suspension>
  #14     WatchPageController.ready (package:yukino_app/ui/pages/anime_page/subpages/watch_page/controller.dart:80)
  <asynchronous suspension>
  
[2022-01-12T00:48:47.151774 ERR!] main: Uncaught error: Null check operator used on a null value
  #0      SearchPageController.onInitState (package:yukino_app/ui/pages/search_page/controller.dart:171)
  #1      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:31)
  #2      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:30)
  #3      _rootRunUnary (dart:async/zone.dart:1434)
  <asynchronous suspension>
  
[2022-01-12T00:49:07.288417 ERR!] main: Uncaught error: Null check operator used on a null value
  #0      SearchPageController.onInitState (package:yukino_app/ui/pages/search_page/controller.dart:171)
  #1      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:31)
  #2      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:30)
  #3      _rootRunUnary (dart:async/zone.dart:1434)
  <asynchronous suspension>
  
[2022-01-12T00:49:32.841487 INFO] select_source: Popping with value
[2022-01-12T00:58:32.440689 INFO] AppLifecycle: Starting "preinitialize"
[2022-01-12T00:58:32.450448 INFO] LocalServer: Finished "initialize"
[2022-01-12T00:58:32.450448 INFO] LocalServer: Serving at http://localhost:59208
[2022-01-12T00:58:34.480527 INFO] DataStore: Initialized "ObjectBox"
[2022-01-12T00:58:34.480527 INFO] AppState: Finished "initialize"
[2022-01-12T00:58:34.484279 INFO] AppLifecycle: Finished "preinitialize"
[2022-01-12T00:58:34.484279 INFO] main: Completed "preinitialize"
[2022-01-12T00:58:34.484279 INFO] main: Starting "MainApp"
[2022-01-12T00:58:34.495991 INFO] InstanceManager: Finished "register"
[2022-01-12T00:58:34.597494 INFO] ProtocolHandler: Finished "register"
[2022-01-12T00:58:34.597494 INFO] Screen: Finished "initialize"
[2022-01-12T00:58:36.316248 INFO] VideoPlayerManager: Finished "initialize"
[2022-01-12T00:58:37.367419 INFO] ExtensionsManager: Finished "initialize"
[2022-01-12T00:58:37.368395 INFO] Trackers: Finished "initialize"
[2022-01-12T00:58:47.615084 ERR!] main: Uncaught error: Null check operator used on a null value
  #0      SearchPageController.onInitState (package:yukino_app/ui/pages/search_page/controller.dart:171)
  #1      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:31)
  #2      _SearchPageState.initState.<anonymous closure> (package:yukino_app/ui/pages/search_page/view.dart:30)
  #3      _rootRunUnary (dart:async/zone.dart:1434)
  <asynchronous suspension>
  
[2022-01-12T00:59:05.945842 INFO] select_source: Popping with value
  
  
  
</details>
 
 ## Checklist
 -   [x] I have read the [Contribution Guidelines](https://yukino-app.github.io/wiki/developers/contribution/#contribution).

**Comment by zyrouge** [comment]
High CPU usage is caused by the embedded VLC player. The detailed explanation can be found [here](https://github.com/alexmercerind/dart_vlc/issues/184). This issue currently cannot be fixed by me but I'll keep this open until an option for external player is available.
