### ISSUE TITLE
[Bug] Fail to load dynamic library error on android

### ISSUE THREAD

**Issue by Latenighthunter** [zyrouge/yukino-app#176]
**Describe the bug**
When I open the app it gives me an error saying Fail to load dynamic library error.

**To Reproduce**
I just open the app and it gives me the error

**Expected behavior**
I expected the application to open and take me to the home page.

**Screenshots**
![image](https://user-images.githubusercontent.com/72238548/149213372-9157da42-3b3f-453f-9425-a7ee3df8a0c6.png)

**Environment (please complete the following information):**

-   Android
-    5

**Additional context**
This is the error it give me

`Message: Something horribly went wrong.
Error: Invalid argument(s): Failed to load dynamic library 'libobjectbox-jni.so': dlopen failed: library "libobjectbox-jni.so" not found
Stack trace:
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _tryObjectBoxLibFile (package:objectbox/src/native/bindings/bindings.dart:56)
#3      loadObjectBoxLib (package:objectbox/src/native/bindings/bindings.dart:66)
#4      C (package:objectbox/src/native/bindings/bindings.dart:84)
#5      new Model (package:objectbox/src/native/model.dart)
#6      new Store (package:objectbox/src/native/store.dart:105)
#7      openStore (package:yukino_app/modules/database/objectbox/objectbox.g.dart:136)
#8      DatabaseManager.initialize (package:yukino_app/modules/database/database.dart:20)
<asynchronous suspension>
#9      AppLifecycle.preinitialize (package:yukino_app/modules/app/lifecycle.dart:76)
<asynchronous suspension>
#10     main (package:yukino_app/main.dart:10)
<asynchronous suspension>`

 ## Checklist
 -   [x] I have read the [Contribution Guidelines](https://yukino-app.github.io/wiki/developers/contribution/#contribution).

**Comment by zyrouge** [comment]
Seems like objectbox doesn't support any android version below 8, there is an on-going pull request for supporting older version https://github.com/objectbox/objectbox-dart/pull/328. I'll keep this open until it's fixed.
