### ISSUE TITLE
[Bug] Error when install extension

### ISSUE THREAD

**Issue by winterdl** [zyrouge/yukino-app#180]
**Describe the bug**
Install clean app, goto extentions tab, chose one extension to install.
The console log with this error:

```
2022-02-08 09:21:35.472775+0700 Runner[23188:4381254] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: File: anonymous_script_14a0ca18: external class Clo...
Thrown Line: 543, Purged Line: 7, Column: 21
Syntactic error: unexpected
Message: Expected [=], met [:].

#0      Hetu.handleError (package:hetu_script/interpreter/interpreter.dart:250)
#1      Hetu.evalSource (package:hetu_script/interpreter/interpreter.dart:304)
#2      HTAbstractInterpreter.eval (package:hetu_script/interpreter/abstract_interpreter.dart:144)
#3      ExtensionInternals.transpileToAnimeExtractor (package:extensions/core/internals.dart:44)
<asynchronous suspension>
#4      ExtensionsManager._addExtension (package:yukino_app/modules/extensions/extensions.dart:126)
<asynchronous suspension>
#5      ExtensionsManager.install (package:yukino_app/modules/extensions/extensions.dart:46)
<asynchronous suspension>
#6      _ExtensionPopupState.build.<anonymous closure> (package:yukino_app/ui/pages/store_page/extensions_page/extensions_page.dart:293)
<asynchronous suspension>
```

the script: https://raw.githubusercontent.com/yukino-app/extensions-store/dist/extensions/zyrouge.twist_moe.ht

line 7, column 21 is: 

```
const baseURL = 'https://twist.moe';
const apiURL = 'https://api.twist.moe/api';

const _twistDecryptKey = '267041df55ca2b36f2e322d05ee2c9cf';
const _twistAccessToken = '0df14814b9e590a1f26d3071a4ed7974';

const defaultHeaders**:** Map<str> = {
    'User-Agent': httpUserAgent(),
    'Referer': baseURL,
    'x-access-token': _twistAccessToken,
}
```

flutter 2.8.2, ios, yukino version: 1.0.14-beta.0

**Comment by zyrouge** [comment]
The extensions have changed alot since the past update, I have to migrate the app to extensions@v1. It's gonna take atleast a week for me to get back.
