### ISSUE TITLE
Getting 404 Not Found Right After The Loading Screen

### ISSUE THREAD

**Issue by Nezzst** [zyrouge/yukino-app#181]
Using the latest windows release, right after the loading screen the error I have described in the title and below appears. 

Message: Something horribly went wrong.
Error: FormatException: Unexpected character (at character 4)
404: Not Found
   ^

Stack trace:
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:892)
#2      _parseJson (dart:convert-patch/convert_patch.dart:40)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      ExtensionsManager._loadStore (package:yukino_app/modules/extensions/extensions.dart:79)
<asynchronous suspension>
#6      ExtensionsManager.initialize (package:yukino_app/modules/extensions/extensions.dart:34)
<asynchronous suspension>
#7      AppLifecycle.initialize (package:yukino_app/modules/app/lifecycle.dart:112)
<asynchronous suspension>
#8      _PageState.initState.<anonymous closure> (package:yukino_app/ui/pages/stacked_home_page/splash_page.dart:42)
<asynchronous suspension>
#9      HooksState.markReady (package:yukino_app/modules/state/hooks.dart:14)
<asynchronous suspension>

**Comment by zyrouge** [comment]
It was caused due to merging the new extensions system. The current app is currently not capable of working with it as if now.
